# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jointstate_info.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'jointstate_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15jointstate_info.proto\x12\tsimulator\"\xfa\x01\n\x0eJointStateInfo\x12\x12\n\njoint_name\x18\x01 \x01(\t\x12\x34\n\x08position\x18\x02 \x01(\x0b\x32\".simulator.JointStateInfo.Position\x12\x34\n\x08velocity\x18\x03 \x01(\x0b\x32\".simulator.JointStateInfo.Velocity\x12\x0e\n\x06\x65\x66\x66ort\x18\x04 \x01(\x02\x1a+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a+\n\x08Velocity\x12\x0f\n\x07\x61ngular\x18\x01 \x01(\x02\x12\x0e\n\x06linear\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jointstate_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTSTATEINFO']._serialized_start=37
  _globals['_JOINTSTATEINFO']._serialized_end=287
  _globals['_JOINTSTATEINFO_POSITION']._serialized_start=199
  _globals['_JOINTSTATEINFO_POSITION']._serialized_end=242
  _globals['_JOINTSTATEINFO_VELOCITY']._serialized_start=244
  _globals['_JOINTSTATEINFO_VELOCITY']._serialized_end=287
# @@protoc_insertion_point(module_scope)
